// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAi1eW6L9udQXx3DOzhAN0F3YJT6IXfiE',
    appId: '1:92133913504:android:9dc1c7bc63b68b11036ac5',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
    androidClientId: '92133913504-29q6dn3gtsmjrsdg1vfchuglsn93cmbm.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcPFQkAuZYZIKBu2Yv7HwIbJvtZhZnGWc',
    appId: '1:92133913504:ios:e1c1d8e7c7c7c7c7',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
    iosClientId: '92133913504-abc123def456.apps.googleusercontent.com',
    iosBundleId: 'ke.cybershujaa.app',
  );
}
