// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAi1eW6L9udQXx3DOzhAN0F3YJT6IXfiE',
    appId: '1:92133913504:web:admin_web_app',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
    authDomain: 'cyberguard-d5f18.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAi1eW6L9udQXx3DOzhAN0F3YJT6IXfiE',
    appId: '1:92133913504:android:9dc1c7bc63b68b11036ac5',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcPFQkAuZYZIKBu2Yv7HwIbJvtZhZnGWc',
    appId: '1:92133913504:ios:e1c1d8e7c7c7c7c7',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
    iosClientId: '92133913504-abc123def456.apps.googleusercontent.com',
    iosBundleId: 'ke.cybershujaa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcPFQkAuZYZIKBu2Yv7HwIbJvtZhZnGWc',
    appId: '1:92133913504:macos:admin_macos_app',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
    iosClientId: '92133913504-abc123def456.apps.googleusercontent.com',
    iosBundleId: 'ke.cybershujaa.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAi1eW6L9udQXx3DOzhAN0F3YJT6IXfiE',
    appId: '1:92133913504:windows:admin_windows_app',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCAi1eW6L9udQXx3DOzhAN0F3YJT6IXfiE',
    appId: '1:92133913504:linux:admin_linux_app',
    messagingSenderId: '92133913504',
    projectId: 'cyberguard-d5f18',
    storageBucket: 'cyberguard-d5f18.firebasestorage.app',
    databaseURL: 'https://cyberguard-d5f18-default-rtdb.firebaseio.com',
  );
}
